import type { ActionWorkspaceSnapshot } from "@sapphire/core-types";

const reuss = { id: "actor-reuss", name: "Reuss", role: "Director", initials: "R" };
const maya = { id: "actor-maya", name: "Maya Chen", role: "Closer", initials: "MC" };
const idris = { id: "actor-idris", name: "Idris Cole", role: "Research", initials: "IC" };

export const actionsFixture: ActionWorkspaceSnapshot = {
  generatedAt: "2026-08-07T08:30:00.000Z",
  actor: reuss,
  missions: [
    {
      id: "mission-copper",
      title: "Secure copper cathode mandate",
      objective: "Qualify buyers and verify two compliant suppliers for a 5,000 MT monthly mandate.",
      status: "at_risk",
      priority: "critical",
      health: "at_risk",
      owner: maya,
      progressPercent: 62,
      targetAt: "2026-08-14T17:00:00.000Z",
      nextMilestone: "Director approval of buyer pricing position",
      openActionCount: 5,
      blockerCount: 2,
      commercialContext: "Copper Cathodes · Europe / Zambia",
      valueExposure: { amount: 42600, currency: "GBP", basis: "expected commission", asOf: "2026-08-07T08:30:00.000Z" },
    },
    {
      id: "mission-gold",
      title: "Verify gold supplier network",
      objective: "Establish five evidence-backed supplier profiles ready for commercial qualification.",
      status: "active",
      priority: "high",
      health: "attention",
      owner: idris,
      progressPercent: 74,
      targetAt: "2026-08-18T17:00:00.000Z",
      nextMilestone: "Complete ownership and export-evidence review",
      openActionCount: 4,
      blockerCount: 1,
      commercialContext: "Gold · Africa / Middle East",
    },
    {
      id: "mission-bank",
      title: "Complete transaction banking readiness",
      objective: "Close onboarding evidence gaps before the first settlement instruction.",
      status: "active",
      priority: "high",
      health: "healthy",
      owner: reuss,
      progressPercent: 81,
      targetAt: "2026-08-21T17:00:00.000Z",
      nextMilestone: "Submit source-of-funds evidence pack",
      openActionCount: 3,
      blockerCount: 0,
      commercialContext: "Finance · Banking",
    },
  ],
  actions: [
    {
      id: "action-pricing",
      title: "Approve buyer pricing position",
      requiredOutcome: "Confirm the protected pricing range before the buyer offer is issued.",
      itemKind: "approval_request",
      status: "ready",
      priority: "critical",
      owner: reuss,
      contributors: [maya],
      dueAt: "2026-08-07T11:00:00.000Z",
      dueState: "due_today",
      mission: { id: "mission-copper", title: "Secure copper cathode mandate", health: "at_risk" },
      sourceWorkspace: "Governance",
      links: [
        { id: "approval-42", type: "approval", label: "SPA pricing authority · AP-042", workspace: "Governance", href: "/governance/approvals/approval-42" },
        { id: "opportunity-cu", type: "opportunity", label: "EU Copper Cathode Mandate", workspace: "Opportunities", href: "/opportunities/opportunity-cu" },
      ],
      blockedReason: null,
      waitingReason: null,
      expectedResumeAt: null,
      authorityRequired: true,
      evidenceRequired: true,
      completionOutcomeRequired: true,
      rankScore: 98,
      rankFactors: ["Director authority required", "Due today", "£42.6k expected commission exposed"],
      commercialConsequence: "Buyer offer remains held; pricing exposure increases after 11:00.",
      updatedAt: "2026-08-07T08:16:00.000Z",
    },
    {
      id: "action-kyc",
      title: "Resolve supplier KYC evidence gap",
      requiredOutcome: "Obtain and verify beneficial-ownership evidence for the shortlisted Zambian supplier.",
      itemKind: "review",
      status: "blocked",
      priority: "critical",
      owner: maya,
      contributors: [idris],
      dueAt: "2026-08-06T16:00:00.000Z",
      dueState: "overdue",
      mission: { id: "mission-copper", title: "Secure copper cathode mandate", health: "at_risk" },
      sourceWorkspace: "Supply",
      links: [{ id: "supplier-zm", type: "company", label: "Zambia Refined Metals Ltd", workspace: "Profiles", href: "/profiles/supplier-zm" }],
      blockedReason: "Beneficial-owner passport certification is missing.",
      waitingReason: null,
      expectedResumeAt: null,
      authorityRequired: false,
      evidenceRequired: true,
      completionOutcomeRequired: true,
      rankScore: 94,
      rankFactors: ["Overdue", "Critical-path blocker", "Supplier verification incomplete"],
      commercialConsequence: "The supplier cannot enter verified matching or receive mandate documents.",
      updatedAt: "2026-08-06T17:40:00.000Z",
    },
    {
      id: "action-followup",
      title: "Call Sofia Marin about copper mandate",
      requiredOutcome: "Confirm Sofia's mandate interest, objections, next request and agreed follow-up.",
      itemKind: "follow_up",
      status: "in_progress",
      priority: "high",
      owner: maya,
      contributors: [],
      dueAt: "2026-08-07T15:30:00.000Z",
      dueState: "due_today",
      mission: { id: "mission-copper", title: "Secure copper cathode mandate", health: "at_risk" },
      sourceWorkspace: "Actions",
      links: [
        { id: "profile-sofia", type: "profile", label: "Sofia Marin · Iberian Metals", workspace: "Profiles", href: "/profiles/profile-sofia" },
        { id: "opportunity-cu", type: "opportunity", label: "EU Copper Cathode Mandate", workspace: "Opportunities", href: "/opportunities/opportunity-cu" },
        { id: "thread-buyers", type: "inbox_thread", label: "Copper buyer qualification thread", workspace: "Inbox", href: "/inbox/thread-buyers" },
      ],
      blockedReason: null,
      waitingReason: null,
      expectedResumeAt: null,
      authorityRequired: false,
      evidenceRequired: false,
      completionOutcomeRequired: true,
      rankScore: 86,
      rankFactors: ["Due today", "Three active buyer conversations", "Mission target at risk"],
      commercialConsequence: "Delayed qualification weakens this week's supplier negotiation position.",
      updatedAt: "2026-08-07T08:02:00.000Z",
    },
    {
      id: "action-bank",
      title: "Submit source-of-funds evidence pack",
      requiredOutcome: "Provide the bank with the approved evidence bundle and receive submission confirmation.",
      itemKind: "task",
      status: "waiting",
      priority: "high",
      owner: reuss,
      contributors: [],
      dueAt: "2026-08-08T12:00:00.000Z",
      dueState: "upcoming",
      mission: { id: "mission-bank", title: "Complete transaction banking readiness", health: "healthy" },
      sourceWorkspace: "Finance",
      links: [{ id: "document-sof", type: "document", label: "Source of Funds Evidence Pack v3", workspace: "Documents", href: "/documents/document-sof" }],
      blockedReason: null,
      waitingReason: "Finance counsel is completing the final evidence index.",
      expectedResumeAt: "2026-08-08T09:00:00.000Z",
      authorityRequired: false,
      evidenceRequired: true,
      completionOutcomeRequired: false,
      rankScore: 78,
      rankFactors: ["External dependency", "Settlement prerequisite", "Expected tomorrow"],
      commercialConsequence: "Settlement instructions cannot be released until onboarding completes.",
      updatedAt: "2026-08-07T07:45:00.000Z",
    },
    {
      id: "action-gold",
      title: "Review gold supplier export evidence",
      requiredOutcome: "Classify provenance, recency and contradictions across the uploaded evidence.",
      itemKind: "review",
      status: "ready",
      priority: "normal",
      owner: idris,
      contributors: [],
      dueAt: "2026-08-09T16:00:00.000Z",
      dueState: "upcoming",
      mission: { id: "mission-gold", title: "Verify gold supplier network", health: "attention" },
      sourceWorkspace: "Documents",
      links: [{ id: "doc-export", type: "document", label: "Supplier export dossier", workspace: "Documents", href: "/documents/doc-export" }],
      blockedReason: null,
      waitingReason: null,
      expectedResumeAt: null,
      authorityRequired: false,
      evidenceRequired: true,
      completionOutcomeRequired: true,
      rankScore: 65,
      rankFactors: ["Mission evidence gate", "Due in two days"],
      commercialConsequence: "Two supplier profiles remain provisional until evidence is classified.",
      updatedAt: "2026-08-07T07:32:00.000Z",
    },
  ],
  journals: {
    "action-followup": [
      { id: "act-dir-1", entryKind: "activity", occurredAt: "2026-08-07T08:04:00.000Z", actor: reuss, entryType: "instruction", visibilityScope: "assigned_users", body: "Confirm Sofia's monthly volume, destination port and whether the buyer can provide a signed mandate this week.", structuredContent: { priority: "critical" }, sourceWorkspace: "Actions", provenanceKind: "human_entry", links: [{ linkedType: "profile", linkedId: "profile-sofia", label: "Sofia Marin", workspace: "Profiles" }], canCreateFollowUp: false },
      { id: "evt-call-start", entryKind: "execution_event", occurredAt: "2026-08-07T08:12:00.000Z", actor: maya, entryType: "state_transition", visibilityScope: null, body: "Action moved from ready to in progress.", structuredContent: { from: "ready", to: "in_progress" }, sourceWorkspace: "Actions", provenanceKind: "system_calculation", links: [], canCreateFollowUp: false },
      { id: "act-call-1", entryKind: "activity", occurredAt: "2026-08-07T08:18:00.000Z", actor: maya, entryType: "call_attempt", visibilityScope: "assigned_users", body: "First call reached voicemail. Left a concise request to reconnect before 10:00.", structuredContent: { channel: "phone", attempt_number: 1, contact_reached: false }, sourceWorkspace: "Activity", provenanceKind: "human_entry", links: [{ linkedType: "inbox_thread", linkedId: "thread-buyers", label: "Buyer qualification thread", workspace: "Inbox" }], canCreateFollowUp: true },
      { id: "act-call-2", entryKind: "activity", occurredAt: "2026-08-07T08:27:00.000Z", actor: maya, entryType: "call_connected", visibilityScope: "mission_team", body: "Sofia confirmed interest in 5,000 MT monthly, CIF Valencia. She needs assay evidence and an indicative range before issuing the mandate.", structuredContent: { channel: "phone", duration_minutes: 7, contact_reached: true, sentiment: "constructive", next_step: "Send assay evidence and indicative range by 12:00" }, sourceWorkspace: "Activity", provenanceKind: "human_entry", links: [{ linkedType: "opportunity", linkedId: "opportunity-cu", label: "EU Copper Cathode Mandate", workspace: "Opportunities" }], canCreateFollowUp: true },
      { id: "act-outcome-1", entryKind: "activity", occurredAt: "2026-08-07T08:29:00.000Z", actor: maya, entryType: "outcome", visibilityScope: "mission_team", body: "Buyer interest is confirmed. Assay evidence and an indicative pricing range are the agreed prerequisites for a signed mandate.", structuredContent: { outcome_status: "qualified", follow_up_due: "2026-08-07T12:00:00.000Z" }, sourceWorkspace: "Activity", provenanceKind: "human_entry", links: [], canCreateFollowUp: true },
    ],
    "action-gold": [
      { id: "act-research-1", entryKind: "activity", occurredAt: "2026-08-07T07:36:00.000Z", actor: idris, entryType: "research_update", visibilityScope: "workspace_team", body: "Two Zambian refinery candidates identified. Export history is plausible; beneficial ownership remains unverified.", structuredContent: { candidate_count: 2, confidence: "medium", quality_note: "Ownership evidence pending" }, sourceWorkspace: "Activity", provenanceKind: "human_entry", links: [{ linkedType: "document", linkedId: "doc-export", label: "Supplier export dossier", workspace: "Documents" }], canCreateFollowUp: true },
      { id: "evidence-gold-1", entryKind: "evidence", occurredAt: "2026-08-07T07:39:00.000Z", actor: idris, entryType: "evidence_linked", visibilityScope: null, body: "Export licence extracts linked as governed evidence.", structuredContent: { evidence_type: "document", verification: "pending" }, sourceWorkspace: "Documents", provenanceKind: "system_calculation", links: [{ linkedType: "document", linkedId: "doc-export", label: "Supplier export dossier", workspace: "Documents" }], canCreateFollowUp: false },
      { id: "act-ai-1", entryKind: "activity", occurredAt: "2026-08-07T07:42:00.000Z", actor: idris, entryType: "ai_summary", visibilityScope: "workspace_team", body: "AI summary: both candidates have evidence gaps in ownership and export recency; no verified-supplier claim is supported yet.", structuredContent: { confidence: "low", model: "Sapphire AI" }, sourceWorkspace: "Activity", provenanceKind: "ai_assisted_preparation", provenanceLabel: "AI-generated · review required", links: [], canCreateFollowUp: false },
    ],
    "mission-copper": [
      { id: "act-mission-1", entryKind: "activity", occurredAt: "2026-08-07T08:00:00.000Z", actor: reuss, entryType: "instruction", visibilityScope: "mission_team", body: "Protect mandate credibility: confirm buyer need before releasing governed pricing or supplier documents.", structuredContent: { review_point: "midday" }, sourceWorkspace: "Actions", provenanceKind: "human_entry", links: [], canCreateFollowUp: false },
      { id: "evt-mission-1", entryKind: "execution_event", occurredAt: "2026-08-07T08:30:00.000Z", actor: reuss, entryType: "state_transition", visibilityScope: null, body: "Mission health assessed as at risk with two active blockers.", structuredContent: { health: "at_risk", blockers: 2 }, sourceWorkspace: "Actions", provenanceKind: "system_calculation", links: [], canCreateFollowUp: false },
    ],
  },
};
